{% set name = "cfanalytics" %}
{% set version = "0.1.10" %}
{% set sha256 = "9bc849d164a8067312aba75862e35c2c3b2b353adaa503d2bbb3285cc6893e94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - aiohttp
    - pandas

test:
  imports:
    - cfanalytics
    - cfanalytics.core
    - cfanalytics.tests

about:
  home: https://github.com/raybellwaves/cfanalytics
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Downloading, analyzing and visualizing CrossFit data'

extra:
  recipe-maintainers:
    - raybellwaves
