travis:
  secure:
    BINSTAR_TOKEN: S3XuMcluMeqmVEUlbe1UJ99+x+SydsXKpxnmibQ3V5CgF924VV7xlHAoBv7d0FOnoCUVqHsOMfY0nI0PkOeKQYDsdoRXBSG5jT5NbKlg0nGT5G13+QXW+EzEP4VMkF1eVb2ouOGJk6i/XoaQQ06jH+9YiwP2OkPWNOeyHWQxZXJQL935GMkaK9+qMSIqHgAFet0yWVTi4EdFddjWcAGfRVzRdBCb4OtkdAGg6/vqZmuweN1Feys8rjdJ20Hya/jytMtg1xXRFxpUojK/dmLc66y97PIRzCND1ufEpTsIzDP7+I9zZmyJdTC8nZXjP0vFzdn8RU4BUCZl7hBp7Bcn0We0CYxAnNHxiBix/w3JHbl8RlXFAV3K2sh8+qJNKFILmZyKPblH4Gqkzka72gK8htbbR/XIovOerpGBCiHiuFmMXmDaqNeXRILkqUJg7Pv2DemvkQRJKEnmlsz/aEcM1EknTSEHWz8ICk6SlcVOsyIXRt9D29/z1Sa/ooLSp6yiwBuqEo/ABC2egIKwJE8PZvFgLGl+IHsS1lXC4n33C487pSxPyeetZWJghnLrIUcmGbnnDN4ksA/74epuC7yRWVOJRqvcsvyu0s2l7lTyR6LCd5rVqKuGCyboIstKoqdmBtMpZ0Cp+drdfjFkwEb6WcrSHSV6tUrJZcxTlEEx2Z0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
