travis:
  secure:
    BINSTAR_TOKEN: naHa8lRBNPWRDBEY5bp4s6x/AmwBHk3GUSMihN5CE4z/UrJbqS1dQwdTVTsyGQDdEdv4GjCgfpGw9DS9CWnC+sMQ9dlN37kwvSIlciAiL4xDHt110qMgiGZ8LiUOw4q/P5VYrqrw94NogJ+BVhzr0gnEga6MdtCQsqC290L+kNdrZoN30Z5JghJjnzpfwli2Z5h5E2DvdjrFB1xGBlVeL/BscbyozzH9iy+yNv0JR2YW/pHdKnXLgW3fU6Wp6sbZgu6DihPBeYekskRSO0hw5+O8nnqAkWjU8a2xa+rAgKhxoxjukckkI1SUzmcqY9XCY/MnrQ/yo47IEtelZxUaVmruaGSFG2je7JCzybmIzcBd3z9tlIb2OBEako78CxjI+5DPdXL4zSIvUFw17v+ZfqJ4ambp9QG/UHk9gxxGE/1Qvw4D8lf+neE9M+gYzqdQnXIJHA9xAGRdOeMB1lGfFulVV0hIhLVqAIBRbzRyMnWWmwyQqvdb7BA3+LpOrBj7YgvyAMKZCF7tZ63YRR11IIcdp/V2iO6lf5VrC+Z2arFrBLLa5ZhlrdgOFl1gn4bwmWL5OKvPyBnI7PyD4Eoj3/HJaxJO7UIRC+MtiDY3zJjqbWrzUV3EgY7K3SvTA3r/VXkjG8wc/OC/3kbzIqey3B7001uXAAZZjqSJkSiEPeM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
