travis:
  secure:
    BINSTAR_TOKEN: ORGXkMUJXGGyE+2SU4FBkQbuS3My5bAECsgE0knfABujkkMS1p5F5wAJCYTwNQ/wBczW5YXFaR1IUer7/gfGVRobX++jQUU7OQlMAuVPAA3O2fhfG0PCTPgs997c/aQ/K0GxTmg0zXbeinI3t42zsSwdev7q5zWKGfU66vkyEo5GTSUm8dSSuzryK+QMokryPOZdiy1yaimhcXb0GFgMwuApoVMBz69dDrzHEkmyC08zZ895rq/FDHdNDhLEAzLWDteuMx5Jym6X8mIKRjTFj/thu/1dHdeojRQS68GkWEXcRFZFFGRRVh/FR71nqL2EvUMXamLUFHfOkz1fQdSCb+BLV03saxGGAmV+m/NUH9EGqFYxW4Y2en9Mb6qb4BnMpingu99PX3UCtorUywC0N074s/ScJaHyaKRDZZxb2j7ISnO8Jj6mom4ANgqXV3GjZ0E4og2pJKPmYwTrtUt0JVDeBZooXJyDzHpA/HVIp91sfrtXIN7YnaKAxi4r2KrFQO+IzNKE8vNUba+OqNwpiUlAiITPt6c/LUPxGb0B5aqMWTBJXi3xElDf5JZ08ibiv+rB/iMnwGa8NSiusKSucj/+Is0jC5+1ExpPvgm2tcszxzHBRF4D3n+hm5QR6TeC01EqlOG3iNXjAl/yuAd0EzJg/njd7orj1w+Q3v9XVpM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
