travis:
  secure:
    BINSTAR_TOKEN: gUss6+11hk7lLGcMXoA2ALfn6mt5OD5ALrx/GJjDPb/DZKqpxDDcBVtPTUtkmYKCyn5u+dhBHnRZa50pWlsnVJpliqGeWWlFP5eDTQKj5BbTa3wonPXcNPNP8KnI57YLYqcDEt/vb3RqZ4aZxdqUKkleH8pxJoodIn39dwSWW+y5C1X/e9qTLUWe/1OZDS1qOY4OOPv48+OP+zsuhDPa0s1C52R8GjfiCQIhC+EQem7WqHGd9pARTYWvJxQlulivQNIQb7oVpWYg4V48XMaDl8fF76i6iNZ5g3W88x7SI4ypnrLTvIubGgIV55B+ewg204WV5GTbldu2jPFAnLzTwRwU4zhWft3UjoWTxoekpkPOU3ivAjEGHFQQ4RR5HyZDSTh4jUTXRkdq8+amrai6NEHc1roM4licooj0wX2UmWMLDz5dtETey8KTuMusud4WpoRQRGrr2P9SbG72fRMc99AXbr74KYhFDh8HxU6031W8VmPr6ZjUIwatbD8jHFUg8TVkNmz3SXMSsJJDWBc1MsgMZ/vh1JWeUIm2fW8ryYSzyMQEgL3GEU2GF77CiJZK7OoP677TzJFVdaRsXXGhz9i92m/pVuaDyycOChGxiS8BE1Vn29cwhtCcoLq1ZRzzBV7EszHA6ZL/Q3q7nsqiBVXW1JMF5iQ3QLhJX0lDbu8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
